### ISSUE TITLE
"Sinan dist" not running

### ISSUE THREAD

**Issue by shlokspeare** [tsloughter/epubnub_chat#1]
Am new to Erlang-OTP. was following your excellent tutorial on http://blog.erlware.org/tag/simple_one_for_one/

1) How do we launch the release? sinan dist doesnt seem to work. Unable to understand this code snippet = {ok, Server} = epubnub_chat_sup:connect("chat"). 

2) I have tried using the rebar way, but unable to go beyond this point:

Saguns-Mac-mini:rel N-Exchanges$ ./epubnub_chat/bin/epubnub_chat start
Node is already running!
Saguns-Mac-mini:rel N-Exchanges$ ./epubnub_chat/bin/epubnub_chat attach
pong
Attaching to /tmp//Users/N-Exchanges/dropbox/gito/epubnub_chat/rel/epubnub_chat/erlang.pipe.1 (^D to exit)
(epubnub_chat@127.0.0.1)1> {ok, Server} = epubnub_chat_sup:connect("chat").  
*\* exception error: undefined function epubnub_chat_sup:connect/1    <<<<Not sure why we execute this >>>>
(epubnub_chat@127.0.0.1)2> epubnub_chat:message(Server, <"hello there!">).
- 2: syntax error before: '<'

3) How does the pubnub servers authenticate me when i send a chat?

Any further links or tutorials will be helpful. thank you for these tutorials.

**Comment by tsloughter** [comment]
This was never updated for the changes I made to epubnub, so it isn't going to work.
